name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker pull ngueyepmodeste/jennapp:v2

      - name: Lint Dockerfile (optionnel)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Installer yamllint
        run: sudo apt-get install -y yamllint

      - name: Lint fichiers YAML
        run: yamllint .
